# Hurricane Season Analysis

## Data Gathering

### Pseudocode
1.  import dependencies
2.  get csv file
3.  read csv file into pandas
4.  display
5.  cleanup/delete unnecessary columns
6.  add columns for data to be calculated

In [148]:
import pandas as pd
import citipy as cipy

In [136]:
file = "hurricane_data.csv"

In [143]:
total_weather_data = pd.read_csv(file, dtype=str, skipinitialspace=True)

In [144]:
total_weather_data.head()

,Time,Landfall,Type,Latitude,Longitude,Max Wind,Min Pressure,34_NE,34_SE,34_SW,34_NW,50_NE,50_SE,50_SW,50_NW,64_NE,64_SE,64_SW,64_NW,Null
18510625,0000,NaN,HU,28.0N,94.8W,80,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,NaN
18510625,0600,NaN,HU,28.0N,95.4W,80,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,NaN
18510625,1200,NaN,HU,28.0N,96.0W,80,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,NaN
18510625,1800,NaN,HU,28.1N,96.5W,80,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,NaN
18510625,2100,L,HU,28.2N,96.8W,80,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,NaN

In [145]:
condensed_weather_data = total_weather_data.drop(columns = ["34_NE","34_SE", "34_SW", "34_NW", "50_NE","50_SE", "50_SW", "50_NW", "64_NE","64_SE", "64_SW", "64_NW", "Null" ])

In [147]:
condensed_weather_data["Name"] = ""
condensed_weather_data["Storm ID"] = ""
condensed_weather_data["Start Date"] = ""
condensed_weather_data["End Date"] = ""
condensed_weather_data["Duration"] = ""
condensed_weather_data["Category"] = ""
condensed_weather_data["Nearest City"] = ""
condensed_weather_data

,Time,Landfall,Type,Latitude,Longitude,Max Wind,Min Pressure,Name,Hurricane ID,Start Date,End Date,Duration,Category,Nearest City
18510625,0000,NaN,HU,28.0N,94.8W,80,-999,,,,,,,
18510625,0600,NaN,HU,28.0N,95.4W,80,-999,,,,,,,
18510625,1200,NaN,HU,28.0N,96.0W,80,-999,,,,,,,
18510625,1800,NaN,HU,28.1N,96.5W,80,-999,,,,,,,
18510625,2100,L,HU,28.2N,96.8W,80,-999,,,,,,,
18510626,0000,NaN,HU,28.2N,97.0W,70,-999,,,,,,,
18510626,0600,NaN,TS,28.3N,97.6W,60,-999,,,,,,,
18510626,1200,NaN,TS,28.4N,98.3W,60,-999,,,,,,,
18510626,1800,NaN,TS,28.6N,98.9W,50,-999,,,,,,,
18510627,0000,NaN,TS,29.0N,99.4W,50,-999,,,,,,,
18510627,0600,NaN,TS,29.5N,99.8W,40,-999,,,,,,,
18510627,1200,NaN,TS,30.0N,100.0W,40,-999,,,,,,,
18510627,1800,NaN,TS,30.5N,100.1W,40,-999,,,,,,,
18510628,0000,NaN,TS,31.0N,100.2W,40,-999,,,,,,,
AL021851,UNNAMED,1,NaN,NaN,NaN,NaN,NaN,,,,,,,
18510705,1200,NaN,HU,22.2N,97.6W,80,-999,,,,,,,
AL031851,UNNAMED,1,NaN,NaN,NaN,NaN,NaN,,,,,,,
18510710,1200,NaN,TS,12.0N,60.0W,50,-999,,,,,,,
AL041851,UNNAMED,49,NaN,NaN,NaN,NaN,NaN,,,,,,,
18510816,0000,NaN,TS,13.4N,48.0W,40,-999,,,,,,,
18510816,0600,NaN,TS,13.7N,49.5W,40,-999,,,,,,,
18510816,1200,NaN,TS,14.0N,51.0W,50,-999,,,,,,,
18510816,1800,NaN,TS,14.4N,52.8W,50,-999,,,,,,,
18510817,0000,NaN,TS,14.9N,54.6W,60,-999,,,,,,,
18510817,0600,NaN,TS,15.4N,56.5W,60,-999,,,,,,,
18510817,1200,NaN,HU,15.9N,58.5W,70,-999,,,,,,,
18510817,1800,NaN,HU,16.1N,60.4W,70,-999,,,,,,,
18510818,0000,NaN,HU,16.6N,62.5W,80,-999,,,,,,,
18510818,0600,NaN,HU,16.9N,64.1W,80,-999,,,,,,,
18510818,1200,NaN,HU,17.2N,66.0W,90,-999,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
AL182017,PHILIPPE,7,NaN,NaN,NaN,NaN,NaN,,,,,,,
20171027,1800,NaN,DB,17.5N,84.2W,30,1006,,,,,,,
20171028,0000,NaN,DB,18.2N,84.5W,30,1006,,,,,,,
20171028,0600,NaN,DB,19.1N,84.3W,30,1004,,,,,,,
20171028,1200,NaN,TD,20.1N,83.5W,30,1003,,,,,,,
20171028,1800,NaN,TS,21.3N,82.4W,35,1000,,,,,,,
20171028,2200,L,TS,22.2N,81.6W,35,1000,,,,,,,
20171029,0000,NaN,TD,22.7N,81.2W,30,1003,,,,,,,
AL192017,RINA,21,NaN,NaN,NaN,NaN,NaN,,,,,,,
20171104,1200,NaN,LO,25.5N,52.3W,25,1013,,,,,,,
20171104,1800,NaN,LO,26.5N,52.1W,25,1013,,,,,,,
20171105,0000,NaN,LO,27.5N,52.0W,25,1013,,,,,,,
20171105,0600,NaN,LO,28.4N,52.0W,25,1013,,,,,,,
20171105,1200,NaN,LO,29.0N,51.9W,25,1013,,,,,,,
20171105,1800,NaN,TD,29.2N,51.7W,30,1012,,,,,,,
20171106,0000,NaN,TD,29.1N,51.2W,30,1011,,,,,,,
20171106,0600,NaN,TD,29.0N,50.7W,30,1010,,,,,,,
20171106,1200,NaN,TD,29.1N,50.4W,30,1010,,,,,,,
20171106,1800,NaN,TD,29.4N,50.2W,30,1009,,,,,,,
20171107,0000,NaN,TS,30.0N,50.0W,35,1008,,,,,,,
20171107,0600,NaN,TS,30.8N,49.9W,40,1006,,,,,,,
20171107,1200,NaN,TS,31.8N,49.5W,40,1004,,,,,,,
20171107,1800,NaN,TS,33.0N,49.1W,40,1002,,,,,,,
20171108,0000,NaN,TS,34.6N,48.7W,45,999,,,,,,,
20171108,0600,NaN,TS,36.4N,48.7W,50,996,,,,,,,
20171108,1200,NaN,TS,38.3N,48.8W,45,994,,,,,,,
20171108,1800,NaN,TS,40.1N,49.0W,45,992,,,,,,,
20171109,0000,NaN,TS,41.8N,48.8W,45,991,,,,,,,
20171109,0600,NaN,LO,43.6N,48.0W,40,993,,,,,,,
20171109,1200,NaN,LO,45.5N,47.0W,40,995,,,,,,,

## Data Cleanup

### Pseudocode
1. 
2. 
3. 
4.

## Visualization and Analysis
1. Have the storms gotten stronger for the past 15 years?
2. What month/season has the strongest storms?
3. How long does storms generally last
4. Where is the most dangerous places to live

### Pseudocode
1. 
2. 
3.

# Strength of Storm

In [ ]:
for row in condensed_weather_data:
        If condensed_weather_data[""] == 'AL':
            then Name =

In [ ]:
#dataframe for strength of storm
storm_strength_df = condensed_weather_data[[]]

# Storm Season

In [ ]:
#dataframe for storm season
storm_season_df = condensed_weather_data[[]]

# Storm Duration

In [ ]:
storm_duration_df = condensed_weather_data[[]]

# Most Dangerous City in relationship to Storms

In [ ]:
stormiest_city_df = condensed_weather_data[[]]