# Hurricane Season Analysis

## Data Gathering

### Pseudocode
1.  import dependencies
2.  get csv file
3.  read csv file into pandas
4.  display
5.  cleanup/delete unnecessary columns
6.  add columns for data to be calculated

In [59]:
import pandas as pd
from citipy import citipy
from datetime import datetime

In [27]:
file = "hurricane_data.csv"

In [34]:
total_weather_data = pd.read_csv(file, dtype=str, skipinitialspace=True)

In [63]:
total_weather_data.head()

,Time,Landfall,Type,Latitude,Longitude,Max Wind,Min Pressure,34_NE,34_SE,34_SW,34_NW,50_NE,50_SE,50_SW,50_NW,64_NE,64_SE,64_SW,64_NW,Null
18510625,0000,NaN,HU,28.0N,94.8W,80,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,NaN
18510625,0600,NaN,HU,28.0N,95.4W,80,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,NaN
18510625,1200,NaN,HU,28.0N,96.0W,80,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,NaN
18510625,1800,NaN,HU,28.1N,96.5W,80,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,NaN
18510625,2100,L,HU,28.2N,96.8W,80,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999,NaN

In [36]:
condensed_weather_data = total_weather_data.drop(columns = ["34_NE","34_SE", "34_SW", "34_NW", "50_NE","50_SE", "50_SW", "50_NW", "64_NE","64_SE", "64_SW", "64_NW", "Null" ])

In [37]:
condensed_weather_data["Name"] = ""
condensed_weather_data["Storm ID"] = ""
condensed_weather_data["Start Date"] = ""
condensed_weather_data["End Date"] = ""
condensed_weather_data["Duration"] = ""
condensed_weather_data["Category"] = ""
condensed_weather_data["Nearest City"] = ""
condensed_weather_data.head()

,Time,Landfall,Type,Latitude,Longitude,Max Wind,Min Pressure,Name,Storm ID,Start Date,End Date,Duration,Category,Nearest City
18510625,0000,NaN,HU,28.0N,94.8W,80,-999,,,,,,,
18510625,0600,NaN,HU,28.0N,95.4W,80,-999,,,,,,,
18510625,1200,NaN,HU,28.0N,96.0W,80,-999,,,,,,,
18510625,1800,NaN,HU,28.1N,96.5W,80,-999,,,,,,,
18510625,2100,L,HU,28.2N,96.8W,80,-999,,,,,,,

In [38]:
#strip the Direction from the Latitude and Longitude
lats = condensed_weather_data["Latitude"].str.split("([A-Z]+)", expand=True)
lons = condensed_weather_data["Longitude"].str.split("([A-Z]+)", expand=True)
#grab the number from index 0
lats = lats[0]
lons = lons[0]
#use citipy to find the nearest city
condensed_weather_data.loc[:, "Latitude"] = lats
condensed_weather_data.loc[:, "Longitude"] = lons
#change the column to numeric
condensed_weather_data["Latitude"] = pd.to_numeric(condensed_weather_data["Latitude"])
condensed_weather_data["Longitude"] = pd.to_numeric(condensed_weather_data["Longitude"])
#convert Longitude column to negative
condensed_weather_data["Longitude"] *= -1

TypeError: 'Series' object is not callable

In [40]:
#use citipy to find the nearest city
latitude = condensed_weather_data["Latitude"]
longitude = condensed_weather_data["Longitude"]
coordinates = zip(latitude, longitude)
cities = []
for coordinate_pair in coordinates:
    lat, lon = coordinate_pair
    cities.append(citipy.nearest_city(lat, lon))

In [56]:
#figure out the city name
city_name = []
for city in cities:
    name = city.city_name
    city_name.append(name)
condensed_weather_data.loc[:, "Nearest City"] = city_name
condensed_weather_data.head()

,Time,Landfall,Type,Latitude,Longitude,Max Wind,Min Pressure,Name,Storm ID,Start Date,End Date,Duration,Category,Nearest City
18510625,0000,NaN,HU,28.0,-94.8,80,-999,,,,,,,freeport
18510625,0600,NaN,HU,28.0,-95.4,80,-999,,,,,,,freeport
18510625,1200,NaN,HU,28.0,-96.0,80,-999,,,,,,,port lavaca
18510625,1800,NaN,HU,28.1,-96.5,80,-999,,,,,,,port lavaca
18510625,2100,L,HU,28.2,-96.8,80,-999,,,,,,,rockport

In [53]:
landfall_city = condensed_weather_data["Landfall"] == "L"
condensed_weather_data[landfall_city]

,Time,Landfall,Type,Latitude,Longitude,Max Wind,Min Pressure,Name,Storm ID,Start Date,End Date,Duration,Category,Nearest City
18510625,2100,L,HU,28.2,-96.8,80,-999,,,,,,,rockport
18510823,2100,L,HU,30.1,-85.7,100,-999,,,,,,,panama city
18511019,1500,L,TS,41.1,-71.7,50,-999,,,,,,,charlestown
18520826,0600,L,HU,30.2,-88.6,100,961,,,,,,,pascagoula
18520912,0000,L,HU,28.0,-82.8,70,-999,,,,,,,dunedin
18521009,2100,L,HU,29.9,-84.4,90,-999,,,,,,,tallahassee
18540626,1200,L,HU,26.2,-97.0,70,-999,,,,,,,brownsville
18540908,2000,L,HU,31.7,-81.1,100,950,,,,,,,richmond hill
18540918,2100,L,HU,28.9,-95.3,90,-999,,,,,,,freeport
18550916,0300,L,HU,29.2,-89.5,110,-999,,,,,,,chalmette
18560810,1800,L,HU,29.2,-91.1,130,934,,,,,,,morgan city
18560819,1100,L,TS,34.8,-76.4,50,-999,,,,,,,havelock
18560831,0600,L,HU,30.2,-85.9,90,-999,,,,,,,panama city
18570913,0000,L,HU,33.9,-78.0,90,-999,,,,,,,wilmington
18570930,1000,L,TS,25.8,-97.0,50,-999,,,,,,,matamoros
18580914,1500,L,TS,27.6,-82.7,60,-999,,,,,,,saint pete beach
18580916,1700,L,HU,40.9,-72.2,80,-999,,,,,,,old saybrook
18580916,1800,L,HU,41.4,-72.0,70,979,,,,,,,groton
18590916,0000,L,HU,30.3,-88.1,70,-999,,,,,,,fairhope
18591017,1600,L,TS,26.4,-80.1,60,-999,,,,,,,boca raton
18591028,1800,L,HU,27.7,-82.8,80,-999,,,,,,,saint pete beach
18600811,2000,L,HU,29.2,-90.0,110,-999,,,,,,,estelle
18600915,0400,L,HU,29.3,-89.6,90,-999,,,,,,,chalmette
18601002,1700,L,HU,29.5,-91.4,90,-999,,,,,,,morgan city
18610927,1700,L,HU,34.5,-77.4,70,-999,,,,,,,piney green
18611007,1200,L,TS,35.3,-75.3,50,-999,,,,,,,elizabeth city
18611101,0800,L,TS,26.0,-81.8,60,-999,,,,,,,naples
18611102,1000,L,HU,34.7,-76.6,70,-999,,,,,,,havelock
18611103,0800,L,TS,41.0,-72.3,60,-999,,,,,,,old saybrook
18611103,0900,L,TS,41.2,-72.0,60,-999,,,,,,,groton
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20161005,0000,L,HU,20.1,-74.3,115,949,,,,,,,baracoa
20161007,0000,L,HU,26.7,-79.0,115,937,,,,,,,freeport
20161008,1500,L,HU,33.0,-79.5,75,967,,,,,,,mount pleasant
20161124,1730,L,HU,11.0,-83.8,100,975,,,,,,,pital
20170620,0200,L,TS,10.1,-61.1,45,1008,,,,,,,rio claro
20170620,0900,L,TS,10.6,-62.6,45,1008,,,,,,,carupano
20170622,0700,L,TS,29.8,-93.7,45,991,,,,,,,port arthur
20170731,1445,L,TS,27.5,-82.7,50,1001,,,,,,,south bradenton
20170808,0345,L,TS,19.1,-87.6,50,995,,,,,,,felipe carrillo puerto
20170810,0500,L,HU,20.0,-96.6,70,990,,,,,,,emilio carranza
20170818,1000,L,TS,13.1,-59.6,40,1004,,,,,,,bridgetown
20170818,1500,L,TS,13.2,-61.2,40,1004,,,,,,,layou
20170826,0300,L,HU,28.0,-96.9,115,937,,,,,,,rockport
20170826,0600,L,HU,28.2,-97.1,105,948,,,,,,,rockport
20170830,0800,L,TS,29.8,-93.5,40,991,,,,,,,orange
20170906,0545,L,HU,17.7,-61.8,155,914,,,,,,,codrington
20170906,1115,L,HU,18.1,-63.1,155,914,,,,,,,marigot
20170906,1630,L,HU,18.5,-64.4,155,915,,,,,,,road town
20170908,0500,L,HU,21.5,-73.0,135,924,,,,,,,cockburn harbour
20170909,0300,L,HU,22.3,-77.9,145,924,,,,,,,esmeralda
20170910,1300,L,HU,24.7,-81.5,115,931,,,,,,,key west
20170910,1930,L,HU,25.9,-81.7,100,936,,,,,,,naples
20170909,0300,L,HU,20.6,-97.1,65,990,,,,,,,tecolutla
20170919,0115,L,HU,15.4,-61.3,145,922,,,,,,,castle bruce
20170920,1015,L,HU,18.0,-65.9,135,920,,,,,,,maunabo
20171005,1200,L,TS,13.9,-83.5,35,999,,,,,,,puerto cabezas
20171008,0000,L,HU,29.1,-89.2,75,983,,,,,,,chalmette
20171008,0520,L,HU,30.4,-89.0,65,984,,,,,,,gulfport
20171016,1100,L,EX,51.9,-10.4,70,957,,,,,,,dingle
20171028,2200,L,TS,22.2,-81.6,35,1000,,,,,,,alacranes

In [55]:
condensed_weather_data[landfall_city]["Nearest City"].value_counts()

tallahassee           25
houma                 22
havelock              22
wilmington            17
chalmette             16
marathon              15
santa fe              14
elizabeth city        13
key west              12
rockport              12
port arthur           12
callaway              12
galveston             11
morgan city           11
spring hill           11
estelle               10
mount pleasant         9
north myrtle beach     9
freeport               9
marigot                9
destin                 8
gainesville            8
key largo              8
naples                 8
fort walton beach      8
dangriga               7
fairhope               7
lake city              7
myrtle grove           7
andros town            7
                      ..
grand bank             1
cumanayagua            1
mucurapo               1
clute                  1
la antigua             1
milford                1
gautier                1
wareham                1
dingle                 1
micoud                 1
tecolutilla            1
saint-pierre           1
angleton               1
sandy bay              1
manati                 1
slidell                1
ocean city             1
dennery                1
esmeralda              1
saint-marc             1
palkaka                1
micco                  1
campeche               1
aquin                  1
pajapan                1
newport                1
mims                   1
palm city              1
north charleston       1
jaguey grande          1
Name: Nearest City, Length: 301, dtype: int64

## Data Cleanup

### Pseudocode
1. 
2. 
3. 
4.

## Visualization and Analysis
1. Have the storms gotten stronger for the past 15 years?
2. What month/season has the strongest storms?
3. How long does storms generally last
4. Where is the most dangerous places to live

### Pseudocode
1. 
2. 
3.

# Strength of Storm

In [ ]:
#dataframe for strength of storm
storm_strength_df = condensed_weather_data[[]]

# Storm Season

In [ ]:
#dataframe for storm season
storm_season_df = condensed_weather_data[[]]

# Storm Duration

In [ ]:
storm_duration_df = condensed_weather_data[[]]

# Most Dangerous City in relationship to Storms

In [ ]:
stormiest_city_df = condensed_weather_data[[]]